import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head >
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="manifest.json" />


        <meta name="nightmode" content="disable" />

        {/* android */}
        <meta name="theme-color" content="#fff" />
        <meta name="mobile-web-app-capable" content="yes" />


        <meta name="apple-mobile-web-app-capable" content="yes" />
        <link rel="apple-touch-icon" href="icon-192x192.png" />
        <link rel="apple-touch-icon" href="icon-384x384.png" />
        <link rel="apple-touch-icon" href="icon-512x512.png" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />

      </Head>
      <body className='mobile-device'>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
